name: Docker Image CI (build, push registry)
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths-ignore:
      -  "*.md"
  pull_request:
    branches: 
      - "master"
    paths-ignore:
      - "*.md"
       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Get refs - this will be used as tags later on
      shell: bash
      run: |
        echo "::set-output name=sha12::$(echo ${GITHUB_SHA} | cut -c1-12)"
      id: getrefs

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Push
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: "."
        file: "Dockerfile"
        platforms: linux/amd64
        push: true
        tags: |
          f1d094/vlmcsd:${{steps.getrefs.outputs.sha12}}, f1d094/vlmcsd:latest
